version: '3.9'

services: 
 # mongoDB Services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes: 
     - mongo_db:/data/db
  
  # Node API service
  square:
    build:
      context: square
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
  
  cube:
    build:
      context: cube
      dockerfile: Dockerfile
    ports:
      - 4001:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
  
  fibonacci:
    build:
      context: fibonacci
      dockerfile: Dockerfile
    ports:
      - 4002:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
  
  metrics:
    build:
      context: metrics
      dockerfile: Dockerfile
    ports:
      - 4003:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
      - square
      - cube
      - fibonacci
  
  client:
    container_name: client_ui
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 4004:3000
    environment:
      - REACT_APP_METRICS_URL: http://metrics:4003
    depends_on:
      - metrics
    links:
      - "metrics"

volumes:
  mongo_db: {}