version: '3.9'

services: 
 # mongoDB Services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes: 
     - mongo_db:/data/db
  
  # Node API service
  square:
    container_name: square_api
    build:
      context: square
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
  
  cube:
    container_name: cube_api
    build:
      context: cube
      dockerfile: Dockerfile
    ports:
      - 4001:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
  
  fibonacci:
    container_name: fibo_api
    build:
      context: fibonacci
      dockerfile: Dockerfile
    ports:
      - 4002:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
  
  metrics:
    container_name: metrics_api
    build:
      context: metrics
      dockerfile: Dockerfile
    ports:
      - 4003:3000
    networks:
      - shared-network
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
  
  # client:
  #   container_name: client_ui
  #   build:
  #     context: client
  #     dockerfile: dockerfile
  #   ports:
  #     - 4004:3000
  #   networks:
  #     - shared-network
  #   depends_on:
  #     - metrics

networks:
  shared-network:

volumes:
  mongo_db: {}